site_name: Theia
site_description: A simple perception project for the OAK-D
site_url: https://roios.github.io/theia/
repo_url: https://github.com/Roios/theia
repo_name: Roios/theia

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy

nav:
  - Home: index.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
